//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_GemiLimanTakip5.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Admin
    {
        public int ID { get; set; }
         [Required(ErrorMessage ="Kullanýcý Bilgisi Girilmelidir.")]
        public string Kullanici { get; set; }
        [Required(ErrorMessage = "Þifreniz Girilmelidir.")]
        [DataType(DataType.Password)]
        public string Sifre { get; set; }
    }
}
