//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_GemiLimanTakip5.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gemiler
    {
        public int ID { get; set; }
        public int LimanID { get; set; }
        public int SirketID { get; set; }
        public string Yuk { get; set; }
        public string YukTonu { get; set; }
        public string Tonaj { get; set; }
        public string Murettebat { get; set; }
        public string Bayrak { get; set; }
        public System.DateTime CikisTarihi { get; set; }
        public System.DateTime VarisTarihi { get; set; }
        public string BulunduguLiman { get; set; }
        public string VaracagiLiman { get; set; }
        public string SirketAdi { get; set; }
    
        public virtual Limanlar Limanlar { get; set; }
        public virtual Sirketler Sirketler { get; set; }
    }
}
