//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_GemiLimanTakip5.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Limanlar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Limanlar()
        {
            this.Gemiler = new HashSet<Gemiler>();
        }
    
        public int ID { get; set; }
        public string Liman { get; set; }
        public string Sehir { get; set; }
        public string Ulke { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gemiler> Gemiler { get; set; }
    }
}
