//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_GemiLimanTakip5.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MVC_LimanGemiTakipEntities1 : DbContext
    {
        public MVC_LimanGemiTakipEntities1()
            : base("name=MVC_LimanGemiTakipEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Gemiler> Gemiler { get; set; }
        public virtual DbSet<Limanlar> Limanlar { get; set; }
        public virtual DbSet<Sirketler> Sirketler { get; set; }
    }
}
